### ISSUE TITLE
1.20.6 

### ISSUE THREAD

**Issue by DexterSK** [Polymart/PolymartPlugin#5]
```[10:38:10 ERROR]: Error occurred while enabling Polymart v1.2.10 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at Polymart.jar/org.polymart.mcplugin.utils.nbt.NBTUtils.set(NBTUtils.java:19) ~[Polymart.jar:?]
        at Polymart.jar/org.polymart.mcplugin.utils.Utils.newActionStack(Utils.java:70) ~[Polymart.jar:?]
        at Polymart.jar/org.polymart.mcplugin.actions.Search.<clinit>(Search.java:66) ~[Polymart.jar:?]
        at Polymart.jar/org.polymart.mcplugin.Main.onEnable(Main.java:40) ~[Polymart.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2223-224e7c7]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at Polymart.jar/org.polymart.mcplugin.utils.ServerVersion.<clinit>(ServerVersion.java:23) ~[Polymart.jar:?]
        ... 14 more```

**Comment by jojodmo** [comment]
This should be fixed with https://polymart.org/resource/polymart-plugin.323/updates?update=45378
